# -- Model -------------------------------------------------
use_pretrained: true
freeze_backbone: true
backbone_name: "MIT/ast-finetuned-audioset-10-10-0.4593"
num_classes: 4
head_hidden_dim: 256
head_dropout: 0.3

# -- Input -------------------------------------------------
sample_rate: 22050
target_duration: 8
n_mels: 128
max_length: 345

# -- Training ----------------------------------------------
epochs: 50
batch_size: 2
amp: true

# -- Optimizer ---------------------------------------------
lr: 0.00005
weight_decay: 0.0001
rho: 0.05

# -- Loss --------------------------------------------------
loss: ce
label_smoothing: 0.1
focal_gamma: 2.0

# -- Augmentation ------------------------------------------
augment: true
use_specaugment: false
use_mixup: false
use_waveaug: false

# -- Scheduler ---------------------------------------------
scheduler: cosine
